'project_id_env': 'CROWDIN_PROJECT_ID'
'api_token_env': 'CROWDIN_PERSONAL_TOKEN'
'base_path': './src/intl'
'base_url': 'https://api.crowdin.com'

'preserve_hierarchy': true

files:
  [
    {
      'source': '/cbuilder.json',
      'translation': '/dictionaries/%locale%.json',
      'dest': '/cbuilder/src/intl/cbuilder.json',
      'type': 'json',
    },
  ]
